### ISSUE TITLE
You can be much more space efficient if you write the code in JS rather than in JSON

### ISSUE THREAD

**Issue by SheetJSDev** [kawanet/iconv-cp932#1]
Instead of storing the entire thing as a big table, just store contiguous blocks and reconstruct the table.  As an example, from the same table you used, https://github.com/SheetJS/js-codepage/blob/master/bits/932.js is about a third of the size.

**Comment by kawanet** [comment]
Thanks. Now shipped with the smaller table as below.
https://github.com/kawanet/iconv-cp932/blob/master/mappings/cp932.json
